### PR TITLE
Pass turn implement for after moving a piece

### PR DESCRIPTION
**Pull request by smlovin2**
- Adds ative_player_id to the games to keep track of who's turn it is
- Adds pass_turn method to the game model that sets the sets the active player to the other player
- Piece controller now passes the turn to the other player after the current active player moves a piece

### CODE REVIEW

**Comment by smlovin2** [comment]
@mscoutermarsh Was wondering how we wanted to handle starting the game and setting the active player. The white player always goes first so are we just automatically starting the game and setting active_player to the white player once the white player joins the game?

**Comment by zenkbaries** [comment]
Can you merge it soon   seems i will need some of those method for my stalemate

**Comment by smlovin2** [comment]
@zenkbaries Yep I'll merge it right now. I was just waiting for you or mike to take a look at.

**Comment by zenkbaries** [comment]
@smlovin2 thanks!! appreciate it

**Comment by smlovin2** [comment]
@zenkbaries No problem!

**Pull request merged**
